<?xml version="1.0" encoding="UTF-8"?>
<!--
  eaf-to-tei.xsl
  Extracts unique lexical items from an ELAN .eaf file and renders them
  as TEI Lex-0 / TEI Dictionaries conformant XML.

  The transform groups annotations by orthographic headword, collects
  IPA forms, glosses, etymologies, and example sentences, producing
  one TEI <entry> per unique orthographic type.

  TEI elements used:
    <entry>        — lexical entry
    <form>         — headword form container
      <orth>       — orthographic form
      <pron notation="IPA"> — phonetic transcription
    <gramGrp>      — grammatical group (from gloss tier tags)
    <sense>        — sense container
      <cit type="translation"> — translated gloss
        <quote>    — the translation string
      <cit type="example"> — example sentence
        <quote>    — vernacular example
        <cit type="translation"> — translated example
    <etym>         — etymology block
      <lang>       — language of etymon
      <mentioned>  — etymon form
      <gloss>      — etymon translation

  ITS 1.0 marks IPA and etymology as its:translate="no" via xml:id
  anchored its:rules (XLIFF-style embed not native to TEI, so we use
  processing instructions and TEI <note> with @type="ITS-no-translate").

  Namespaces:
    TEI  — http://www.tei-c.org/ns/1.0
    ITS  — http://www.w3.org/2005/11/its (as PI wrapper)

  Parameters:
    source-lang     BCP-47 vernacular code
    target-lang     primary gloss/translation language
    trans-prefix    EAF tier ID prefix for translations
    orth-tier, ipa-tier, morph-tier, gloss-tier, etym-tier — tier prefixes
-->
<xsl:stylesheet
  xmlns:xsl = "http://www.w3.org/1999/XSL/Transform"
  xmlns:tei = "http://www.tei-c.org/ns/1.0"
  xmlns:its = "http://www.w3.org/2005/11/its"
  version   = "2.0"
  exclude-result-prefixes="its">

  <xsl:output method="xml" encoding="UTF-8" indent="yes"/>
  <xsl:strip-space elements="*"/>

  <xsl:param name="source-lang"   select="'und'"/>
  <xsl:param name="target-lang"   select="'en'"/>
  <xsl:param name="trans-prefix"  select="'trans-'"/>
  <xsl:param name="orth-tier"     select="'orth'"/>
  <xsl:param name="ipa-tier"      select="'ipa'"/>
  <xsl:param name="morph-tier"    select="'morph'"/>
  <xsl:param name="gloss-tier"    select="'gloss'"/>
  <xsl:param name="etym-tier"     select="'etym'"/>

  <xsl:key name="ref-by-parent"  match="ANNOTATION/REF_ANNOTATION" use="@ANNOTATION_REF"/>
  <xsl:key name="ts-by-id"       match="TIME_SLOT"                  use="@TIME_SLOT_ID"/>

  <!-- ============================================================
       Root → TEI document
       ============================================================ -->
  <xsl:template match="/ANNOTATION_DOCUMENT">

    <!-- Collect all orth texts across the file -->
    <xsl:variable name="all-orth-anns"
      select="//TIER[starts-with(@TIER_ID,$orth-tier)]
                //ANNOTATION/REF_ANNOTATION"/>

    <TEI xmlns="http://www.tei-c.org/ns/1.0"
         xmlns:its="http://www.w3.org/2005/11/its"
         its:version="1.0">

      <!-- Embedded ITS rules for TEI consumers -->
      <its:rules version="1.0">
        <its:translateRule selector="//tei:pron"    translate="no"/>
        <its:translateRule selector="//tei:etym"    translate="no"/>
        <its:translateRule selector="//tei:note[@type='ITS-no-translate']"
                           translate="no"/>
      </its:rules>

      <teiHeader>
        <fileDesc>
          <titleStmt>
            <title>Lexical wordlist extracted from ELAN annotation file</title>
          </titleStmt>
          <publicationStmt>
            <p>Generated by eaf-to-tei.xsl from
              <xsl:value-of select="HEADER/MEDIA_DESCRIPTOR[1]/@RELATIVE_MEDIA_URL"/>
            </p>
          </publicationStmt>
          <sourceDesc>
            <p>ELAN Annotation Format
              version <xsl:value-of select="@FORMAT"/></p>
          </sourceDesc>
        </fileDesc>
        <profileDesc>
          <langUsage>
            <language ident="{$source-lang}">Vernacular / object language</language>
            <language ident="{$target-lang}">Analysis language</language>
          </langUsage>
        </profileDesc>
      </teiHeader>

      <text>
        <body>
          <!--
            Group orth annotations by unique whitespace-tokenized word form.
            Each unique vernacular word type becomes one TEI <entry>.
          -->
          <xsl:for-each-group
            select="$all-orth-anns"
            group-by="ANNOTATION_VALUE">
            <xsl:sort select="current-grouping-key()"/>

            <xsl:variable name="key"       select="current-grouping-key()"/>
            <xsl:variable name="first-ann" select="current-group()[1]"/>
            <xsl:variable name="first-id"  select="$first-ann/@ANNOTATION_ID"/>

            <!-- IPA for first occurrence -->
            <xsl:variable name="ipa"
              select="key('ref-by-parent',$first-id)
                          [ancestor::TIER[starts-with(@TIER_ID,$ipa-tier)]][1]
                          /ANNOTATION_VALUE"/>

            <!-- Gloss via morph chain -->
            <xsl:variable name="morph-id"
              select="key('ref-by-parent',$first-id)
                          [ancestor::TIER[starts-with(@TIER_ID,$morph-tier)]][1]
                          /@ANNOTATION_ID"/>
            <xsl:variable name="gloss"
              select="key('ref-by-parent',$morph-id)
                          [ancestor::TIER[starts-with(@TIER_ID,$gloss-tier)]][1]
                          /ANNOTATION_VALUE"/>

            <!-- Etymology JSON blob from EAF -->
            <xsl:variable name="etym-json"
              select="key('ref-by-parent',$first-id)
                          [ancestor::TIER[starts-with(@TIER_ID,$etym-tier)]][1]
                          /ANNOTATION_VALUE"/>

            <!-- Translations: collect all trans-* tier children of
                 the parent utterance of each orth annotation -->
            <xsl:variable name="parent-ann-id"
              select="$first-ann/@ANNOTATION_REF"/>
            <xsl:variable name="trans-anns"
              select="key('ref-by-parent',$parent-ann-id)
                          [ancestor::TIER[starts-with(@TIER_ID,$trans-prefix)]]"/>

            <entry xmlns="http://www.tei-c.org/ns/1.0"
                   xml:id="{concat('e_',generate-id($first-ann))}">

              <!-- Headword form -->
              <form>
                <orth xml:lang="{$source-lang}">
                  <xsl:value-of select="$key"/>
                </orth>
                <!-- IPA: its:translate="no" via @notation -->
                <xsl:if test="normalize-space($ipa)!=''">
                  <pron notation="IPA" its:translate="no"
                        xmlns:its="http://www.w3.org/2005/11/its">
                    <xsl:value-of select="$ipa"/>
                  </pron>
                </xsl:if>
              </form>

              <!-- Grammatical group: parsed from Leipzig gloss notation
                   (last word of gloss = POS tag if all-caps) -->
              <xsl:if test="normalize-space($gloss)!=''">
                <xsl:variable name="last-token"
                  select="tokenize(normalize-space($gloss),'\s+')[last()]"/>
                <xsl:if test="$last-token = upper-case($last-token)">
                  <gramGrp>
                    <gram type="pos">
                      <xsl:value-of select="$last-token"/>
                    </gram>
                  </gramGrp>
                </xsl:if>
              </xsl:if>

              <!-- Sense -->
              <sense>
                <!-- Translations as cit type="translation" -->
                <xsl:for-each select="$trans-anns">
                  <xsl:variable name="tier-id"
                    select="ancestor::TIER/@TIER_ID"/>
                  <xsl:variable name="lang"
                    select="if (contains(substring-after($tier-id,$trans-prefix),'@'))
                            then substring-before(
                                   substring-after($tier-id,$trans-prefix),'@')
                            else substring-after($tier-id,$trans-prefix)"/>
                  <xsl:if test="normalize-space(ANNOTATION_VALUE)!=''">
                    <cit type="translation" xml:lang="{$lang}">
                      <quote><xsl:value-of select="ANNOTATION_VALUE"/></quote>
                    </cit>
                  </xsl:if>
                </xsl:for-each>

                <!-- Gloss note (its:translate="no") -->
                <xsl:if test="normalize-space($gloss)!=''">
                  <note type="ITS-no-translate"
                        its:translate="no"
                        xmlns:its="http://www.w3.org/2005/11/its">
                    interlinear-gloss: <xsl:value-of select="$gloss"/>
                  </note>
                </xsl:if>

                <!-- Example sentences: all occurrences of this orth form -->
                <xsl:for-each select="current-group()">
                  <xsl:variable name="eg-orth-id"   select="@ANNOTATION_ID"/>
                  <xsl:variable name="eg-parent-id" select="@ANNOTATION_REF"/>
                  <xsl:variable name="eg-orth"      select="ANNOTATION_VALUE"/>

                  <!-- The full utterance orth text for context -->
                  <xsl:for-each
                    select="key('ref-by-parent',$eg-parent-id)
                                [ancestor::TIER[starts-with(@TIER_ID,$trans-prefix)]]">
                    <xsl:variable name="eg-lang"
                      select="if (contains(
                                substring-after(ancestor::TIER/@TIER_ID,$trans-prefix),'@'))
                              then substring-before(
                                     substring-after(ancestor::TIER/@TIER_ID,$trans-prefix),'@')
                              else substring-after(ancestor::TIER/@TIER_ID,$trans-prefix)"/>
                    <cit type="example">
                      <quote xml:lang="{$source-lang}">
                        <xsl:value-of select="$eg-orth"/>
                      </quote>
                      <xsl:if test="normalize-space(ANNOTATION_VALUE)!=''">
                        <cit type="translation" xml:lang="{$eg-lang}">
                          <quote><xsl:value-of select="ANNOTATION_VALUE"/></quote>
                        </cit>
                      </xsl:if>
                    </cit>
                  </xsl:for-each>
                </xsl:for-each>

              </sense>

              <!-- Etymology block (DMLex etymonUnit JSON → TEI <etym>) -->
              <xsl:if test="normalize-space($etym-json)!=''">
                <etym its:translate="no"
                      xmlns:its="http://www.w3.org/2005/11/its">
                  <!--
                    Parse the JSON blob stored by the EAF etym tier.
                    Format: {"langCode":"...","text":"...","reconstructed":bool,"translation":"..."}
                    We extract via string manipulation (no JSON parser in XSLT 2.0).
                  -->
                  <xsl:variable name="lang-code"
                    select="replace($etym-json,
                              '.*&quot;langCode&quot;\s*:\s*&quot;([^&quot;]+)&quot;.*','$1')"/>
                  <xsl:variable name="etymon-text"
                    select="replace($etym-json,
                              '.*&quot;text&quot;\s*:\s*&quot;([^&quot;]+)&quot;.*','$1')"/>
                  <xsl:variable name="etymon-trans"
                    select="replace($etym-json,
                              '.*&quot;translation&quot;\s*:\s*&quot;([^&quot;]+)&quot;.*','$1')"/>
                  <xsl:variable name="reconstructed"
                    select="contains($etym-json,'&quot;reconstructed&quot;:true')"/>

                  <lang><xsl:value-of select="$lang-code"/></lang>
                  <mentioned>
                    <xsl:if test="$reconstructed">
                      <xsl:attribute name="rend">reconstructed</xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="$etymon-text"/>
                  </mentioned>
                  <xsl:if test="normalize-space($etymon-trans)!=''
                                and $etymon-trans != $etym-json">
                    <gloss><xsl:value-of select="$etymon-trans"/></gloss>
                  </xsl:if>
                </etym>
              </xsl:if>

            </entry>
          </xsl:for-each-group>
        </body>
      </text>
    </TEI>
  </xsl:template>

  <xsl:template match="text()"/>

</xsl:stylesheet>
